# Generated by Django 4.2 on 2023-04-19 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_user_alter_movie_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="added_by",
        ),
    ]
